"use client";

import { useState, useEffect } from "react";
import { darkTheme, lightTheme } from "@/lib/theme";

export interface RecipeData {
  id?: string;
  name: string;
  author: string;
  mood: string;
  bestFor: string;
  settings: { label: string; value: string }[];
}

interface Props {
  recipe: RecipeData;
  sessionId: string;
  onSaved?: (id: string) => void;
  onDeleted?: () => void;
  alreadySaved?: boolean;
  savedId?: string;
}

export default function RecipeCard({ recipe, sessionId, onSaved, onDeleted, alreadySaved = false, savedId }: Props) {
  const [copied, setCopied] = useState(false);
  const [isDark, setIsDark] = useState(true);

  useEffect(() => {
    const saved = localStorage.getItem("xe5_theme");
    setIsDark(saved !== "light");
  }, []);

  const t = isDark ? darkTheme : lightTheme;
  const [starred, setStarred] = useState(alreadySaved);
  const [saving, setSaving] = useState(false);
  const [showPdf, setShowPdf] = useState(false);

  const handleCopy = () => {
    const text = [
      `🎞️ ${recipe.name} — Fujifilm X-E5 Recipe`,
      `By: ${recipe.author}`,
      recipe.mood ? `Mood: ${recipe.mood}` : "",
      recipe.bestFor ? `Best for: ${recipe.bestFor}` : "",
      "",
      ...recipe.settings.map(s => `${s.label}: ${s.value}`),
      "",
      "Generated by XE5 Research Agent",
    ].filter(Boolean).join("\n");
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleStar = async () => {
    if (starred && savedId) {
      // Unsave
      setSaving(true);
      await fetch(`/api/recipes?id=${savedId}`, { method: "DELETE" });
      setStarred(false);
      setSaving(false);
      onDeleted?.();
    } else {
      // Save
      setSaving(true);
      const res = await fetch("/api/recipes", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          session_id: sessionId,
          name: recipe.name,
          author: recipe.author,
          mood: recipe.mood,
          best_for: recipe.bestFor,
          settings: recipe.settings,
        }),
      });
      const data = await res.json();
      setStarred(true);
      setSaving(false);
      if (data.id) onSaved?.(data.id);
    }
  };

  const handlePdfExport = () => {
    const printContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>${recipe.name} — XE5 Recipe</title>
        <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:ital,wght@0,700;0,900;1,400&family=DM+Sans:wght@400;500&family=DM+Mono:wght@400&display=swap" rel="stylesheet">
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: 'DM Sans', sans-serif; background: #f5f0e8; color: #1a1008; }
          .header { background: #0c0a07; padding: 2rem 2.5rem; }
          .label { font-family: 'DM Mono', monospace; font-size: 0.5rem; letter-spacing: 0.3em; color: #4a3e2a; text-transform: uppercase; margin-bottom: 0.5rem; }
          .title { font-family: 'Playfair Display', serif; font-size: 2.5rem; font-weight: 900; color: #e8d5b0; letter-spacing: -0.02em; line-height: 1.1; margin-bottom: 0.4rem; }
          .rule { width: 40px; height: 2px; background: #c8a96e; margin: 0.6rem 0; }
          .author { font-size: 0.7rem; color: #6b5d45; }
          .body { padding: 2rem 2.5rem; }
          .mood { margin-bottom: 1.5rem; padding: 0.85rem 1rem; background: rgba(12,10,7,0.05); border-left: 3px solid #c8a96e; font-style: italic; font-family: 'Playfair Display', serif; font-size: 0.85rem; color: #4a3020; line-height: 1.7; }
          .section-label { font-family: 'DM Mono', monospace; font-size: 0.5rem; letter-spacing: 0.2em; color: #8a7060; text-transform: uppercase; margin-bottom: 0.6rem; }
          table { width: 100%; border-collapse: collapse; margin-bottom: 1.25rem; }
          tr { border-bottom: 1px solid rgba(12,10,7,0.08); }
          td { padding: 0.45rem 0; font-size: 0.75rem; }
          td:first-child { color: #6a5040; width: 55%; }
          td:last-child { font-family: 'DM Mono', monospace; font-weight: 600; color: #1a1008; text-align: right; }
          .best-for { font-size: 0.75rem; color: #4a3020; margin-bottom: 1.5rem; }
          .footer { display: flex; justify-content: space-between; align-items: center; padding-top: 1rem; border-top: 1px solid rgba(12,10,7,0.1); }
          .footer-label { font-family: 'DM Mono', monospace; font-size: 0.5rem; color: #b0a090; letter-spacing: 0.1em; }
          .badge { width: 28px; height: 28px; border-radius: 50%; border: 1.5px solid #c8a96e; display: flex; align-items: center; justify-content: center; font-family: 'DM Mono', monospace; font-size: 0.45rem; color: #c8a96e; letter-spacing: 0.05em; }
          @media print { body { -webkit-print-color-adjust: exact; print-color-adjust: exact; } }
        </style>
      </head>
      <body>
        <div class="header">
          <div class="label">Fujifilm X-E5 · Film Simulation Recipe</div>
          <div class="title">${recipe.name}</div>
          <div class="rule"></div>
          <div class="author">by ${recipe.author}</div>
        </div>
        <div class="body">
          ${recipe.mood ? `<div class="mood">"${recipe.mood}"</div>` : ""}
          <div class="section-label">Camera Settings</div>
          <table>
            ${recipe.settings.map(s => `<tr><td>${s.label}</td><td>${s.value}</td></tr>`).join("")}
          </table>
          ${recipe.bestFor ? `<div class="section-label">Best For</div><div class="best-for">${recipe.bestFor}</div>` : ""}
          <div class="footer">
            <div class="footer-label">XE5 Research Agent · v4.0</div>
            <div class="badge">XE5</div>
          </div>
        </div>
        <script>window.onload = function() { window.print(); }</script>
      </body>
      </html>
    `;
    const win = window.open("", "_blank");
    if (win) { win.document.write(printContent); win.document.close(); }
  };

  const filmSim = recipe.settings.find(s => /film simulation/i.test(s.label));
  const otherSettings = recipe.settings.filter(s => !/film simulation/i.test(s.label));

  return (
    <div style={{ marginTop: "1rem", background: t.bgCard, border: `1px solid ${isDark ? "rgba(200,169,110,0.15)" : "rgba(176,136,64,0.2)"}`, borderRadius: "6px", overflow: "hidden" }}>
      {/* Card header */}
      <div style={{ padding: "1rem 1.25rem 0.9rem", borderBottom: "1px solid rgba(200,169,110,0.1)", background: t.bgCategoryCard, position: "relative" }}>
        <div style={{ position: "absolute", top: 0, right: 0, bottom: 0, width: "3px", background: "repeating-linear-gradient(180deg, #c8a96e 0px, #c8a96e 6px, transparent 6px, transparent 12px)", opacity: 0.25 }} />
        <div style={{ fontSize: "0.52rem", letterSpacing: "0.18em", color: t.textFaint, textTransform: "uppercase", marginBottom: "0.3rem" }}>🎞️ Film Simulation Recipe · X-E5</div>
        <div style={{ fontFamily: "'Playfair Display', serif", fontSize: "1.3rem", fontWeight: 900, color: t.text, letterSpacing: "-0.01em", marginBottom: "0.2rem" }}>{recipe.name}</div>
        <div style={{ fontSize: "0.62rem", color: t.textMuted }}>by {recipe.author}</div>
        {recipe.mood && (
          <div style={{ marginTop: "0.6rem", fontSize: "0.72rem", color: t.textMuted, fontStyle: "italic", lineHeight: 1.6, borderLeft: "2px solid #2a2318", paddingLeft: "0.65rem" }}>
            "{recipe.mood}"
          </div>
        )}
      </div>

      {/* Settings */}
      <div style={{ padding: "0.9rem 1.25rem" }}>
        {filmSim && (
          <div style={{ marginBottom: "0.5rem", padding: "0.5rem 0.7rem", background: t.bgCardUser, border: `1px solid ${isDark ? "rgba(200,169,110,0.2)" : "rgba(176,136,64,0.25)"}`, borderRadius: "3px", display: "flex", justifyContent: "space-between", alignItems: "center" }}>
            <span style={{ fontSize: "0.58rem", color: "#6b5d45", textTransform: "uppercase", letterSpacing: "0.1em" }}>Film Simulation</span>
            <span style={{ fontSize: "0.85rem", color: t.gold, fontWeight: 600, fontFamily: "'DM Mono', monospace" }}>{filmSim.value}</span>
          </div>
        )}
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "0.35rem" }}>
          {otherSettings.map((s, i) => (
            <div key={i} style={{ padding: "0.4rem 0.6rem", background: t.bgInput, border: `1px solid ${t.borderCard}`, borderRadius: "3px" }}>
              <div style={{ fontSize: "0.5rem", color: t.textVeryFaint, letterSpacing: "0.1em", textTransform: "uppercase", marginBottom: "0.12rem" }}>{s.label}</div>
              <div style={{ fontSize: "0.75rem", color: t.text, fontFamily: "'DM Mono', monospace" }}>{s.value}</div>
            </div>
          ))}
        </div>

        {recipe.bestFor && (
          <div style={{ marginTop: "0.5rem", padding: "0.5rem 0.7rem", background: t.bgButton, border: "1px solid #181410", borderRadius: "3px", display: "flex", gap: "0.5rem", alignItems: "center" }}>
            <span style={{ fontSize: "0.8rem" }}>📍</span>
            <div>
              <div style={{ fontSize: "0.5rem", color: "#3a3020", letterSpacing: "0.1em", textTransform: "uppercase" }}>Best for</div>
              <div style={{ fontSize: "0.7rem", color: "#a89070" }}>{recipe.bestFor}</div>
            </div>
          </div>
        )}
      </div>

      {/* Actions */}
      <div style={{ padding: "0.7rem 1.25rem", borderTop: `1px solid ${t.borderCard}`, display: "flex", gap: "0.4rem" }}>
        <button onClick={handleCopy}
          style={{ flex: 1, padding: "0.45rem 0", background: copied ? "rgba(76,175,77,0.12)" : t.bgCardUser, border: `1px solid ${copied ? "rgba(76,175,77,0.3)" : (isDark ? "rgba(200,169,110,0.15)" : "rgba(176,136,64,0.2)")}`, borderRadius: "3px", color: copied ? "#4caf7d" : "#c8a96e", cursor: "pointer", fontSize: "0.62rem", letterSpacing: "0.1em", textTransform: "uppercase", transition: "all 0.2s", fontFamily: "'DM Sans', sans-serif" }}>
          {copied ? "✓ Copied" : "📋 Copy"}
        </button>
        <button onClick={handleStar} disabled={saving}
          style={{ width: "34px", height: "34px", background: starred ? t.bgCardUser : "transparent", border: `1px solid ${starred ? (isDark ? "rgba(200,169,110,0.3)" : "rgba(176,136,64,0.35)") : t.borderCard}`, borderRadius: "3px", cursor: "pointer", fontSize: "0.9rem", display: "flex", alignItems: "center", justifyContent: "center", transition: "all 0.2s" }}
          title={starred ? "Remove from saved" : "Save recipe"}>
          {saving ? "…" : starred ? "⭐" : "☆"}
        </button>
        <button onClick={handlePdfExport}
          style={{ width: "34px", height: "34px", background: "transparent", border: "1px solid #181410", borderRadius: "3px", cursor: "pointer", fontSize: "0.75rem", color: "#4a3e2a", display: "flex", alignItems: "center", justifyContent: "center", transition: "all 0.2s", fontFamily: "'DM Sans', sans-serif" }}
          title="Export as PDF"
          onMouseEnter={e => { e.currentTarget.style.borderColor = "#c8a96e"; e.currentTarget.style.color = "#c8a96e"; }}
          onMouseLeave={e => { e.currentTarget.style.borderColor = "#181410"; e.currentTarget.style.color = "#4a3e2a"; }}>
          PDF
        </button>
      </div>
    </div>
  );
}
